import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

const frizQuadrata = localFont({
  src: [
    {
      path: './fonts/friz-quadrata-std-medium-5870338ec7ef8.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/friz-quadrata-std-bold-587034a220f9f.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/friz-quadrata-std-italic-587033b2c95df.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: './fonts/friz-quadrata-std-bold-italic-587033d6d4298.otf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-friz-quadrata',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={`${frizQuadrata.variable} font-serif antialiased`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
      </html>
  );
}